module.exports = {
    // Basic configuration
    token: 'ODk3NjM4NzczNjcwNjk0OTYy.GdSu0e.x3b1dlc_-kWSczaY26Un1SuQclSmlS3_L6jR0c', // Place here your token
    status: 'v1.0',
    developerGuildID: '959115766630854797', // Place here your Guild ID
    database: 'mongodb+srv://ademiro:9txBLN4OyZDMjYO8@cluster0.ata9znn.mongodb.net/?retryWrites=true&w=majority', // Place here your MongoDB access

    // Ticket configuration 
    ticketName: 'ticket-',
    ticketDescription: '🌿 Ticket open by',
    ticketCreate: '✅ Your ticket has been created',
    ticketAlreadyExist: 'Sorry but you already have an open ticket.',
    ticketNoPermissions: 'Sorry, but you do not have permission to do this.',
    ticketError: 'Something went wrong, try again later.',
    ticketMessageTitle: 'Welcome to you, thanks for opening a ticket.',
    ticketMessageDescription: 'A member of our moderation team will soon take care of your request.\nThanks to you for waiting in calm and good mood.',
    ticketClose: 'Close',
    ticketCloseEmoji: '📪',
    ticketLock: 'Lock',
    ticketLockEmoji: '🔒',
    ticketUnlock: 'Unlock',
    ticketUnlockEmoji: '🔓',
    ticketClaim: 'Claim',
    ticketClaimEmoji: '👋',
    ticketManage: 'Members',
    ticketManageEmoji: '➕',
    ticketManageMenuTitle: 'Choose a member.',
    ticketManageMenuEmoji: '❔',
    ticketCloseTitle: 'The ticket is currently being closed...',
    ticketCloseDescription: 'Ticket will be closed in 5 seconds.',
    ticketSuccessLocked: 'Ticket was locked succesfully.',
    ticketAlreadyLocked: 'This ticket is already locked.',
    ticketSuccessUnlocked: 'Ticket was unlocked succesfully.',
    ticketAlreadyUnlocked: 'This ticket is already unlocked.',
    ticketSuccessClaim: 'Ticket was successfully claimed by',
    ticketAlreadyClaim: 'Ticket is already claimed by',
    ticketDescriptionClaim: ', it was claimed by',
    ticketTranscriptMember: 'Member:',
    ticketTranscriptTicket: 'Ticket:',
    ticketTranscriptClaimed: 'Claimed:',
    ticketTranscriptModerator: 'Moderator:',
    ticketTranscriptTime: 'Time:',
    ticketMemberAdd: 'has been added to the ticket.',
    ticketMemberRemove: 'has been removed to the ticket.',
}